[ERROR]-[2018-05-11 15:12:09,097]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：Message: 

[ERROR]-[2018-05-11 15:15:04,017]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：name 'a' is not defined
[ERROR]-[2018-05-11 15:15:36,215]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：name 'a' is not defined
[ERROR]-[2018-05-11 15:16:30,136]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：Message: 

[ERROR]-[2018-05-11 15:24:59,466]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：Message: 

[ERROR]-[2018-05-11 15:30:20,177]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：Message: 

[ERROR]-[2018-05-11 15:32:43,921]-[Web_Auto]-[mylogger.py]-[My_logger]-日志信息：find_element() takes from 1 to 3 positional arguments but 17 were given
